site_name: "Test Docs"
repo_url: "https://github.com/ASD-Azul/test"
use_directory_urls: true
theme:
  name: "material"
  logo: "assets/images/letter.svg"
  favicon: "assets/images/ico.d.32.png"
  palette:
    - scheme: "slate"
  features:
    - navigation.tabs
    - navigation.indexes

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - privacy
  - offline
  - awesome-nav

extra_css:
  - assets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
