trigger: none
pr:
  - main
  - releases/*
pool:
  name: AppTest Debian
  demands: Agent.OS -equals Linux

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: CyberLab-Services/pipeline-templates
      ref: refs/heads/main
      trigger: none

extends:
  template: v2/stages/test-build-publish.yaml@PipelineTemplates
  parameters:
    repo_name: self
    is_docker: true
